### ISSUE TITLE
Multi-line time series with subquery/CTE

### ISSUE THREAD

**Issue by stas-sl** [grafana/clickhouse-datasource#207] opened 2022-10-03 14:17 UTC
**Describe the bug**
I'm not sure if this bug or just not implemented, but when I'm trying to use a bit more complicated queries that include subqueries or CTEs, the results fail to be recognised as multi time-series data. 

**Versions**
Grafana: 9.1.5
Plugin: 2.0.1

**Query**
For example this query works:
```sql
select $__timeInterval(time) as time, device_id, avg(temp) as temp
from measurements
where $__timeFilter(time)
group by device_id, time
order by time
```

<img width="861" alt="image" src="https://user-images.githubusercontent.com/4602302/193597893-66874a96-4f7a-4b0e-b0de-ac93ddd40d0d.png">

<img width="866" alt="image" src="https://user-images.githubusercontent.com/4602302/193597970-f3fa7e46-31f6-49d4-baae-56258ba441c9.png">

However the following modifications do not:
```sql
select * from (select $__timeInterval(time) as time, device_id, avg(temp) as temp
from measurements
where $__timeFilter(time)
group by device_id, time
order by time)
```
or
```sql
with cte as (select $__timeInterval(time) as time, device_id, avg(temp) as temp
from measurements
where $__timeFilter(time)
group by device_id, time
order by time)
select * from cte
```

<img width="853" alt="image" src="https://user-images.githubusercontent.com/4602302/193596838-c9acbab0-38e8-41fc-8b40-7261f86b99df.png">

<img width="857" alt="image" src="https://user-images.githubusercontent.com/4602302/193596947-7f3b4c5a-0e8a-4303-8c2e-95d18093dd36.png">

**Comment by gingerwizard** [comment] 2022-10-05 12:18
You device_id to be a string

**Comment by stas-sl** [comment] 2022-10-05 13:18
Well, despite it contains numbers, it is a String indeed (LowCardinality(String) to be precise) - you can see it from column header icon "_A_". And if it was a number, it would not work with a simple query as well.

**Comment by gingerwizard** [comment] 2022-10-05 15:52
so you can use a transform to wide series to fix this but I don't understand why this isn't working - ideas @bossinc ?

I can't reproduce with my own sub selects  - I'll try CTEs as well.

**Comment by stas-sl** [comment] 2022-10-05 16:45
Well, plugin reinstallation didn't help. 

My CH version is 22.3.3.44, if it makes any difference.

**Comment by stas-sl** [comment] 2022-10-05 17:17
I don't know why, but when I view results in query inspector `device_id` column is formatted as temperature using ℃. Although, as you see it has "_A_" in column header, and I tried to explicitly convert it to string - `toString(device_id)`. It happens only when I wrap the query in CTE/subquery, otherwise it works well.

<img width="640" alt="image" src="https://user-images.githubusercontent.com/4602302/194119570-8f7a8376-8288-4c50-8777-6b07fb6b3889.png">

And response types look correct to me:
```json
{
  "response": {
    "results": {
      "A": {
        "frames": [
          {
            "schema": {
              "name": "A",
              "refId": "A",
              "meta": {
                "preferredVisualisationType": "table",
                "executedQueryString": "..."
              },
              "fields": [
                {
                  "name": "time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "device_id",
                  "type": "string",
                  "typeInfo": {
                    "frame": "string"
                  }
                },
                {
                  "name": "temp",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64"
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  1663588800000,
                  1663588800000,
                  1663589400000,
                  ....
                ],
                [
                  "1231111",
                  "5449773",
                  "5449773",
                 ....
                ],
                [
                  11.505,
                  14.626666666666667,
                  15.0475,
                   ...
                ]
              ]
            }
          }
        ],
        "refId": "A"
      }
    }
  }
}
```

**Comment by gingerwizard** [comment] 2022-10-05 21:43
Apologies i meant multi-frame not wide. I'll see if I can reproduce tmr.

**Comment by aangelisc** [comment] 2023-06-09 16:04
@gingerwizard did you reproduce this issue?

**Comment by mrsndmn** [comment] 2024-02-02 08:55
I have the same problem with 

**Versions**
Grafana: 10.3.1
Plugin: 4.0.1

**Query**
```
SELECT time as time, s as metric, sum(a) FROM VALUES(
    'time DateTime, s String, a UInt64',
    (toDate(now()), 'one', 1),
    (toDate(now()), 'two', 2),
    (toDate(now()), 'three', 3),
    (toDate(now() - interval 1 day), 'one', 1),
    (toDate(now() - interval 1 day), 'two', 2),
    (toDate(now() - interval 1 day), 'three', 3)
    )
group by time, s
order by time
```

<img width="1166" alt="изображение" src="https://github.com/grafana/clickhouse-datasource/assets/15786586/e8919d4f-56a8-4a5e-9bd1-24ee4409dde5">

<img width="1061" alt="изображение" src="https://github.com/grafana/clickhouse-datasource/assets/15786586/a4e5187b-0d00-404e-babf-c38b910e35e6">


**Multi-frame transform**

Multi-frame transform fixed a problem. Thank you!

<img width="1061" alt="изображение" src="https://github.com/grafana/clickhouse-datasource/assets/15786586/e845fa8b-0d4d-47e3-9ac8-014cc7529ded">

**Comment by aangelisc** [comment] 2024-03-19 20:08
Hi @mrsndmn, if the multi-frame transformation solved this problem for you please let us know. If you're still having problems please create a new issue.

@stas-sl, @gingerwizard I'm going to close this issue as there's been awhile without any activity or response. If this is still an issue please re-open 😊

**Closed by aangelisc** 2024-03-19 20:08 UTC
Labels: datasource/ClickHouse

**Comment by iyuroch** [comment] 2024-03-20 12:19
@aangelisc I'm having the same issue, multiframe seems to help, however as per my understanding it should be working without transformation, do I miss something?

**Comment by loi-nguyenhuynh-shopee** [comment] 2025-02-28 07:05
For me, the `Multi-frame time series` and `Wide time series` transformations both don't work, but it works with 1 simple change in the script

The script without CTE **that works**
```sql
SELECT $timeSeries as t, region, duration
FROM $table
WHERE $timeFilter
GROUP BY t, region
ORDER BY t, region
```
The script with CTE **that doesn't work** (even tho it returns same data frame) - the issue in this thread
```sql
WITH cleaned_data AS (
  SELECT $timeSeries as t, region, duration
  FROM $table
  WHERE $timeFilter
  GROUP BY t, region
  ORDER BY t, region
)
SELECT * FROM cleaned_data
```
The script with CTE **that works**
```sql
WITH cleaned_data AS (
  SELECT $timeSeries as t, region, duration
  FROM $table
  WHERE $timeFilter
  GROUP BY t, region
  ORDER BY t, region
)
SELECT t, groupArray((region, duration)) FROM cleaned_data GROUP BY t
```

**Comment by loia5tqd001** [comment] 2025-02-28 07:06
For me, the `Multi-frame time series` and `Wide time series` transformations both don't work, but it works with 1 simple change in the script

The script without CTE **that works**
```sql
SELECT $timeSeries as t, region, duration
FROM $table
WHERE $timeFilter
GROUP BY t, region
ORDER BY t, region
```
The script with CTE **that doesn't work** (even tho it returns same data frame) - the issue in this thread
```sql
WITH cleaned_data AS (
  SELECT $timeSeries as t, region, duration
  FROM $table
  WHERE $timeFilter
  GROUP BY t, region
  ORDER BY t, region
)
SELECT * FROM cleaned_data
```
The script with CTE **that works**
```sql
WITH cleaned_data AS (
  SELECT $timeSeries as t, region, duration
  FROM $table
  WHERE $timeFilter
  GROUP BY t, region
  ORDER BY t, region
)
SELECT t, groupArray((region, duration)) FROM cleaned_data GROUP BY t
```
