### ISSUE TITLE
Partial or Empty Query Results when Using HTTP Ports 8123/8023 on Clickhouse Datasource Plugin with Grafana 9.3.6

### ISSUE THREAD

**Issue by hjc668** [grafana/clickhouse-datasource#392] opened 2023-05-19 07:51 UTC
**What happened**:

While using Grafana version 9.3.6 and the ClickHouse Datasource Plugin version 3.0.0, I encountered an issue where query results are incomplete or even empty when connecting via HTTP ports 8123 or 8023, particularly when the data volume exceeds approximately 20,000 records. This issue does not occur when using the ClickHouse native port 9000.

**What you expected to happen**:

I expected that the data would be fully and accurately retrieved from the datasource, regardless of the connection method (HTTP or native) or the volume of the data.

**How to reproduce it (as minimally and precisely as possible)**:

1. Connect to a ClickHouse datasource using Grafana 9.3.6 and ClickHouse Datasource Plugin 3.0.0 via HTTP ports 8123 or 8023.
2. Execute a query that yields more than approximately 20,000 records.
3. Observe that the returned data is incomplete or empty.

**Screenshots**:

Attached are comparison tables of the data obtained through different connection methods (HTTP ports vs native port) from the same datasource.

![WechatIMG35462](https://github.com/grafana/clickhouse-datasource/assets/32215218/b630b41f-455c-4c29-b05b-3bde1f17f1fb)

**Anything else we need to know?**:

Given the size of production data, I am obliged to use chproxy. However, chproxy currently does not support connections via port 9000. It's worth noting that this issue was not encountered when I was using Vertamedia ClickHouse Grafana.

**Environment**:

- Grafana version: 9.3.6
- Plugin version: ClickHouse Datasource Plugin 3.0.0

**Comment by jdgeisler** [comment] 2023-05-26 16:15
I have also noticed incorrect, empty, or partial query results when using port 8123. However, I also tested using Clickhouse Datasource Plugin v2.2.0 and v2.2.1 and the issue was still present. Similarly, the correct results were returned using the Vertamedia ClickHouse Grafana, or any other sql editor.

Grafana version: 9.5.1
Clickhouse Datasource plugin version" v2.2.0/v2.2.1/v3.0.0

**Comment by heesuk-ahn** [comment] 2023-05-31 12:24
In my case, a partial result return occurs even when I connect to the clickhouse headless service through port 9000.

Grafana version : v9.3.8
Plugin version : Clickhouse Datasource Plugin 3.0.0

**Comment by mshustov** [comment] 2023-06-02 08:00
@hjc668 @jdgeisler @heesuk-ahn is there an intermediate proxy in your setup? https://github.com/ContentSquare/chproxy maybe?

**Comment by bossinc** [comment] 2023-06-02 21:14
@hjc668 @jdgeisler @heesuk-ahn I am having trouble reproducing this. I have a few questions that might help debug this:
- Are the queries taking a long time to process and then returning no results?
- If you rerun the query, is it always the same?
- What is the query type set to? If they are set to `auto` can you try to set it to a different query type and see if that makes a difference?

**Comment by hjc668** [comment] 2023-06-16 02:24
> @hjc668 @jdgeisler @heesuk-ahn I am having trouble reproducing this. I have a few questions that might help debug this:
> 
> * Are the queries taking a long time to process and then returning no results?
> * If you rerun the query, is it always the same?
> * What is the query type set to? If they are set to `auto` can you try to set it to a different query type and see if that makes a difference?

* Are the queries taking a long time to process and then returning no results?
Yes,even though it only takes just over 9 seconds, it still returns no results or sometimes just one piece of data.
* If you rerun the query, is it always the same?
Yes
* What is the query type set to? If they are set to `auto` can you try to set it to a different query type and see if that makes a difference?
 In my version, there are only two query types - SQL Editor and Query Builder. However, I can only use SQL Editor because Query Builder doesn't support some aggregate functions of ClickHouse's aggregated tables, such as countMerge() and maxMerge().

**Comment by bossinc** [comment] 2023-06-29 16:01
@hjc668 
Is the query format set to auto?
![Screenshot from 2023-06-29 10-59-48](https://github.com/grafana/clickhouse-datasource/assets/5140848/b86bf971-ef45-451e-8573-c334bd0d60c7)

**Comment by hjc668** [comment] 2023-06-30 09:36
> @hjc668 Is the query format set to auto? ![Screenshot from 2023-06-29 10-59-48](https://user-images.githubusercontent.com/5140848/249834001-b86bf971-ef45-451e-8573-c334bd0d60c7.png)

Which version of the clickHouse datasource plugin are you using? I don't have this option in the version 3.0.0 that I am using.
btw,what is the purpose of selecting this option? the type of panel is set to table.
![1861688116793_ pic_hd](https://github.com/grafana/clickhouse-datasource/assets/32215218/443cf7b5-e901-4f36-8ec2-d02061681b8f)

**Comment by mshustov** [comment] 2023-07-03 09:36
> Are the queries taking a long time to process and then returning no results?
Yes,even though it only takes just over 9 seconds, it still returns no results or sometimes just one piece of data.

@hjc668 thank you for helping us to investigate the problem. Since we have challenges reproducing the problem, maybe you could assist us in localizing the root cause. 

- Could you try to perform the same query to ClickHouse via HTTP interface using `curl` or an HTTP client? 
- Could you query ClickHouse with a script using `clickhouse-go v2.10.0`? https://github.com/grafana/clickhouse-datasource/blob/main/go.mod#L6

Having that information would give us a base for further investigation. Thank you!

**Comment by mshustov** [comment] 2023-08-21 16:40
@jdgeisler  @heesuk-ahn  maybe you can help with the investigation? https://github.com/grafana/clickhouse-datasource/issues/392#issuecomment-1617727080

**Comment by alyssabull** [comment] 2024-03-12 16:14
Hey @mshustov! Is this still an issue?

**Comment by mshustov** [comment] 2024-03-17 13:16
@alyssabull, the topic starter didn't answer. We can close the issue and wait until a new report with more details is provided.

**Closed by mshustov** 2024-03-17 13:16 UTC
Labels: type/bug, datasource/ClickHouse
