### ISSUE TITLE
Multi-line time-series not working after clicking on Run Query button

### ISSUE THREAD

**Issue by heanlan** [grafana/clickhouse-datasource#75] opened 2022-02-11 02:29 UTC
release 0.12.0

![image](https://user-images.githubusercontent.com/80798942/153528800-289a896f-1590-4e0e-9f17-58be215a0af5.png)
![image](https://user-images.githubusercontent.com/80798942/153528820-3484ac8c-45d6-4c48-b11a-7e5a4b4e434b.png)
![image](https://user-images.githubusercontent.com/80798942/153528858-1eb8acb7-bdf7-4ba6-b1a8-c651a763c03e.png)

**Comment by scottlepp** [comment] 2022-02-11 15:26
Duplicate of #71

**Closed by scottlepp** 2022-02-11 15:26 UTC
