### ISSUE TITLE
Add "data"/"clickable" links within "log messages fields" (as it is currently done in Loki)

### ISSUE THREAD

**Issue by jmassiot** [grafana/clickhouse-datasource#208] opened 2022-10-03 15:13 UTC
**Is your feature request related to a problem? Please describe.**

We are currently using, for some of our use cases, the "logs panel" visualization.
We would like to be able to "navigate" from the fields of some logs messages:
* currently we have the ability to add some "navigation" in "Time series" panel by defining some "Data links"
* we would like to have the same "navigation" ability from "logs"

Having this kind of ability will greatly improve the usability of our solution.

**Describe the solution you'd like**

This kind of navigation ("internal" or "external URL") is currently possible within the `Loki` plugin by defining the expected navigation in the `Derived fields` settings.
(cf screenshot below)

![image](https://user-images.githubusercontent.com/26866214/193611563-45bc920c-0e4f-475d-81b9-3f10a63b7d38.png)

It will be great if we could have the same ability within the "Clickhouse datasource" plugin:
* by leveraging what is available on the Loki side
* and just adding the ability to define those links through "Derived fields" within the plugin settings

**Describe alternatives you've considered**

**Additional context**
Do you think that it will make sense to have this ability within the plugin ? Does it look achievable ?
If you think it makes sense, it is a topic on which we can try to contribute.

**Comment by gingerwizard** [comment] 2022-10-05 21:44
duplicate of https://github.com/grafana/clickhouse-datasource/issues/154

**Comment by gingerwizard** [comment] 2022-10-07 08:07
Yes its on the roadmap  - i'll see if we can publish an issue with this shortly.

**Comment by jmassiot** [comment] 2022-10-07 13:31
thanks! that's great.
not sure if it will be part of a first version, but on our side, what we would need would be to have the ability to "build" an external URL not only with the values of the "clickable" field but also with the value from other fields from the same log message.

**Comment by gingerwizard** [comment] 2022-10-18 19:00
@bossinc close as duplicate please.

**Closed** 2022-10-18 19:31 UTC
