### ISSUE TITLE
$__fromTime macro error in query builder after upgrade to v 2.0.3

### ISSUE THREAD

**Issue by chayuto** [grafana/clickhouse-datasource#236] opened 2022-11-09 23:30 UTC
**Describe the bug**
$__fromTime macro generate wrong query string in some combination when update from 2.0.1 to 2.0.3

WHERE   ( date  >= $__fromTime AND date <= $__toTime )  GROUP BY ... ORDER BY ... DESC

becomes:
WHERE   ( date  >= toDateTime(intDiv(1665444389770,1000))  DESC

WHERE   ( date  >= toDateTime(intDiv(1665444389770,1000)) "QUREY STRING WENT MISSING"  DESC

resolved when downgrade to 2.0.1 with 
```
docker exec -it grafana /bin/bash

grafana-cli plugins install grafana-clickhouse-datasource 2.0.1

docker restart grafana
```

**Versions**
Grafana v8.3.1 (b9eacd93e9)
 Plugin versions.: 2.0.3

**Query**
WHERE   ( date  >= $__fromTime AND date <= $__toTime ) 

**To Reproduce**
WHERE   ( date  >= $__fromTime AND date <= $__toTime ) 
in complex query

**Screenshots**
![Screen Shot 2022-11-10 at 10 29 25 am](https://user-images.githubusercontent.com/5305832/200964102-66243fc8-9b7b-4a34-a5e7-e72a3f7aee6d.png)

**Additional context**

generate error: 
"error querying the database: clickhouse [execute]:: 400 code: Code: 62. DB::Exception: Syntax error: failed at position 65 ('(') (line 3, col 9): ( date >= toDateTime(intDiv(1665444389770,1000)) DESC. Unmatched parentheses: (. (SYNTAX_ERROR) (version 22.8.5.29 (official build)) "

**Comment by chayuto** [comment] 2022-11-09 23:41
possible that it's broken from changes in v.2.0.2 for query builder 

https://github.com/grafana/clickhouse-datasource/compare/v2.0.1...v2.0.2

**Comment by mshustov** [comment] 2022-11-11 10:14
the problem has been caused by `sqlds` version upgrade in https://github.com/grafana/clickhouse-datasource/pull/223

With `sqlds@2.3.11` version https://github.com/grafana/clickhouse-datasource/tree/8c47f0e50fe70f024d84ac0b6a19dc010436cbbb  `WHERE (...) AND (...)` was parsed correctly:
![2022-11-11_10-48-41](https://user-images.githubusercontent.com/3198181/201317886-5e2d4d42-503b-498b-89f4-e717fd3e10b3.png)
With `sqlds@2.3.13`, the plugin fails to parse `WHERE (...) AND (...)`, even though it works for a query with a single condition `WHERE (...)`
![2022-11-11_10-47-09](https://user-images.githubusercontent.com/3198181/201318065-646ec2ae-a9cc-46cd-8035-6193d657ad1c.png)

@bossinc @sasklacz  Shouldn't it be fixed in the upstream?

**Closed** 2022-12-06 07:58 UTC
Labels: bug
